Footer
lucasxdsy/shopping-cart pull request #2
Opened 2024-03-07 19:32 UTC by Carolllina

2024-03-07 20:06 UTC, DIOGO4810 requested changes

2024-03-07 20:06 UTC, DIOGO4810 commented on components/Footer.tsx
> +const footer = ({viewCart}:PropsType) => {
Normalmente , os nomes dos componentes em React começam com letra maiúscula. Ou seja renomear footer para Footer.
Tanto no nome da "const" como no "export default" 
Espero que o eu ter dado esta critica não estrague ou dê erros no programa :)))

2024-03-13 01:57 UTC, lucasxdsy commented on components/Footer.tsx
> +                Shopping-cart &copy; {year}</div>
Shopping-cart 2024 está a ser repetido tanto aqui como na linha 22. 
Podia-se colocá-lo abaixo do if then else para não ser repetido e trocar-se o if then else por um 'not' viewCart && (o que está no else).
Acho que assim ficava mais simples.

2024-03-13 01:58 UTC, lucasxdsy approved these changes

2024-03-13 22:45 UTC, DIOGO4810 approved these changes

2024-03-13 22:57 UTC, merged